#! /bin/sh

# 1. Launch the Hotkey Daemon (Crucial)
pgrep -x sxhkd > /dev/null || sxhkd &

# 2. Fix the cursor (Standard arrow instead of X)
xsetroot -cursor_name left_ptr &

# 3. Start the Look & Feel tools
picom &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
feh --bg-scale ~/.config/bspwm/wallpaper.jpg &
nm-applet &

# 4. Launch Polybar
$HOME/.config/polybar/launch.sh &

# 5. Monitor Setup (Single monitor default)
bspc monitor -d I II III IV V VI VII VIII IX X

# 6. Window Rules (Optional but good)
bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Colors (Cybersecurity Theme)
bspc config normal_border_color "#4c566a"
bspc config focused_border_color "#5e81ac"